### GENERAL SETTINGS ###

# Site settings
title: Investing for Freedom
subtitle: About investing & financial independence
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."
analytics: #Google analytics code in the format XX-nnnnnnnn-n
baseurl: "" #important: start with /
url: "http://investingforfreedom.com"

# Build settings
markdown: kramdown
permalink: /:categories/:title
excerpt_separator: <!--more--> #use this in posts to define how long the excerpt of the post (that is shown on the Blog page) is

colors:  #in hex code if not noted else
  primary: "#00b3fe" #"#F70031"
  primary_rgb: "0,179,254" #"247,0,49" #rgb of the primary. Needed in some places for the transparency effect.
  secondary: "#384452" #"#33004D"
  link: "#428bca"
  link_hover: "#01b2fe"
  footer_heading: "#ffffff"
  footer_content: "#bfc9d3"

# Short text about your company. Shown in footer on every page and also separately on Home and Contact page.
about: "This blog is about my personal journey of (dividend growth) investing."


# static man config
# see: https://mademistakes.com/articles/jekyll-static-comments/
repository: "janpieterzuidema/blog"
staticman:
  allowedFields          : ['name', 'message']
  branch                 : "master"
  commitMessage          : "New comment"
  filename               : comment-{@timestamp}
  format                 : "yml"
  moderation             : true
  path                   : "_data/comments/{options.slug}"
  requiredFields         : ['name', 'message']
  transforms:
    email                : "md5"
  generatedFields:
    date:
      type               : "date"
      options:
        format           : "iso8601"
